version: 2.1

jobs:
  build:

    docker:
      - image: circleci/node:14.16.1

    parallelism: 1

    steps:
      - checkout
      - restore_cache:
          keys:
            - m1-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run lint
      - save_cache:
          key: m1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  lint-install:
    jobs:
      - build:
        filters:
          branches:
            only:
              - /*main/
              - /release-.*/
